name: Build Workflow
 
on:
  push:
    branches:
      - master
      - development
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
 
      - name: Build project
        run: |
          echo "Building the project..."
          echo "Build completed!"
