name: Call Reusable Workflow
 
on:
  push:
 
jobs:
  call-reusable:
    uses: ./.github/workflows/reusable_workflow.yml
    with:
      name: Shivaji
      environment: production
    secrets:
      my_secret: ${{ secrets.MY_SECRET }}
