name: Comprehensive Workflow
 
on:
  # Trigger on push events with branch, tag, and path filters (separate workflows are needed if you want 'ignore' filters)
  push:
    branches:
      - master
      - development
    tags:
      - v1.*
      - v2.0.0
    paths:
      - README.md
 
  # Trigger on pull request events with activity types and branch filters
  pull_request:
    branches:
      - master
      - release/*
    types:
      - opened
      - reopened
      - synchronize
      - closed
 
  # Trigger on issue events with specific activity types
  issues:
    types:
      - opened
      - edited
      - closed
 
  # Trigger manually with workflow_dispatch and inputs
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment environment (e.g., production or staging)"
        required: true
        default: "production"
      feature_flag:
        description: "Enable feature flag (true/false)"
        required: false
        default: "false"
 
  # Trigger when another workflow finishes
  workflow_run:
    workflows:
      - Build Workflow
    types:
      - completed
 
jobs:
  example_job:
    runs-on: ubuntu-latest
 
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
 
      # Log the branch, tag, and paths triggering the workflow
      - name: Log GitHub Context
        run: |
          echo "Branch: ${{ github.ref_name }}"
          echo "Event: ${{ github.event_name }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Triggered by: ${{ github.actor }}"
 
      # Conditional action based on workflow_dispatch inputs
      - name: Handle Inputs
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Feature Flag: ${{ github.event.inputs.feature_flag }}"
 
      # Additional steps for pull request events
      - name: Pull Request Details
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "Pull Request Title: ${{ github.event.pull_request.title }}"
          echo "Action: ${{ github.event.action }}"
          echo "Branch: ${{ github.event.pull_request.head.ref }}"
          echo "Base Branch: ${{ github.event.pull_request.base.ref }}"
 
      # Additional steps for issue events
      - name: Issue Details
        if: ${{ github.event_name == 'issues' }}
        run: |
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Action: ${{ github.event.action }}"
          echo "Issue Number: ${{ github.event.issue.number }}"
 
      # Steps for triggered workflow_run
      - name: Workflow Run Details
        if: ${{ github.event_name == 'workflow_run' }}
        run: |
          echo "Triggered Workflow: ${{ github.event.workflow_run.name }}"
          echo "Conclusion: ${{ github.event.workflow_run.conclusion }}"
