name: Trigger manual workflow

run-name: Trigger manual

on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: printing massge
        run: echo "manual successfull"
