name: pull_request

run-name: pull_request

on:
 pull_request:
  branches:
   - master
jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: event pull request task
        run: echo "first step is success"
