name: Trigger pull workflow

run-name: Trigger pull

on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: printing massge
        run: echo "pull request worflow successfull"
